### ISSUE TITLE
the outputs of simulating forward model

### ISSUE THREAD

**Issue by Nicko222** [trustimaging/stride#33]
Dear @ccuetom ,
Thanks for your contribution. I would like to if I use Stride to simulate asonic wave propagation in the water, the output of it is from the receivers or the whole  computational domain . e.g., if the numerical grid is 1000 by 1000, the number of receiver is 128 and the time step is 2000. The size of the pressure field is 1000 by 1000 by 2000 or 128 by 2000. I meet some problem while installing Stride and cannot test it. Could you please tell me  the pressure data is from receiver locations or the entire computational grid? Thanks a lot!

**Comment by ccuetom** [comment]
Hey!

The pressure field itself will have a size of 2000x1000x1000 (divided by any undersampling in time that you apply to the saving). The data from the receivers will be 128x2000 every time you fire a source. 

If you have problems with your installation, I would suggest that you use [our Slack channel](https://join.slack.com/t/stridecodes/shared_invite/zt-xr1dlqv7-Lesu9nFYOqF~AjA6VPUdhw) to ask, we would be happy to help you with that.

**Comment by Nicko222** [comment]
> Hey!
> 
> The pressure field itself will have a size of 2000x1000x1000 (divided by any undersampling in time that you apply to the saving). The data from the receivers will be 128x2000 every time you fire a source.
> 
> If you have problems with your installation, I would suggest that you use [our Slack channel](https://join.slack.com/t/stridecodes/shared_invite/zt-xr1dlqv7-Lesu9nFYOqF~AjA6VPUdhw) to ask, we would be happy to help you with that.

Hi @ccuetom ,
Thanks a lot for your reply. I will install it in another machine. Thanks again.
