### ISSUE TITLE
 RuntimeError in homogeneous_acoustic/ forward_2D.py

### ISSUE THREAD

**Issue by Nicko222** [trustimaging/stride#35]
Hello @ccuetom,
I am testing the forward example and don't change anything. However, it shows runtimeError in jupyter notebook. 
'~/anaconda3/envs/usct/lib/python3.8/site-packages/uvloop/loop.pyx in uvloop.loop.Loop.run_until_complete()

~/anaconda3/envs/usct/lib/python3.8/site-packages/uvloop/loop.pyx in uvloop.loop.Loop.run_until_complete()

~/anaconda3/envs/usct/lib/python3.8/site-packages/uvloop/loop.pyx in uvloop.loop.Loop.run_forever()

~/anaconda3/envs/usct/lib/python3.8/site-packages/uvloop/loop.pyx in uvloop.loop.Loop._run()

RuntimeError: Cannot run the event loop while another loop is running'.

Could you please tell me how to fix it?
Thanks a lot

**Comment by ccuetom** [comment]
Could you give me a bit more context? What notebook are you trying to run? What code are you trying to use?

It's a lot easier to discuss these sort of questions in [our Slack channel](https://join.slack.com/t/stridecodes/shared_invite/zt-xr1dlqv7-Lesu9nFYOqF~AjA6VPUdhw), so I'd recommend using it as much as possible.
