### ISSUE TITLE
Normalization of fft in fft.magnitude_spectrum

### ISSUE THREAD

**Issue by dsleiter** [trustimaging/stride#37]
Using `stride.utils.fft.magnitude_spectrum`, I wanted to calculate the amplitude of a steady-state sinusoidal.

```
import numpy as np
from stride.utils import fft

freq = 25.
ppp = 30
dt = 1 / freq / ppp
t = np.arange(5 * ppp) * dt  # five periods
amplitude = 234.  # this is the target amplitude we expect to recover
y = amplitude * np.sin(2 * np.pi * freq * t)

freqs, fft_amps = fft.magnitude_spectrum(y, dt, db=False)
freq_idx = np.argmin(np.abs(freqs - freq))
print(fft_amps[freq_idx])
```

I naively expected the output to be `234.0`, the amplitude of the sinusoidal, but the result is `17550.0`.

Which is the intended result for `magnitude_spectrum`? Is it expected that the user needs to apply a factor to the FFT magnitudes in order to extract the steady-state?

For some context, I investigated the source of the difference:

Based on examples using `np.fft`, it seems like it is common to divide the output fft amplitudes by `N/2` where N is the length of the input array (`len(y)`). In fact, this is the exact scaling factor we see `17550 = 234 * 75`.

The source of the `N/2` seems to be a combination of two things:
1. the choice of FFT normalization
2. the fact that the wave amplitude in frequency space is split over positive and negative frequency components

`np.fft` [documentation](https://numpy.org/doc/stable/reference/routines.fft.html) does not do a great job of explaining this, but I found [this post](https://stackoverflow.com/questions/63211851/why-divide-the-output-of-numpy-fft-by-n) and [this other post](https://electronics.stackexchange.com/questions/25900/scaling-fft-output-by-number-of-points-in-fft) to be useful in understanding.

The result is that if we want to recover the original sinusoidal amplitude, we need to divide the desired fft element magnitude by N / 2 where N is the length of the input array and the factor of two is there because we are only looking at the positive frequency element.

Alternatively, we could us the `forward` normalization and sum the amplitude in the positive and negative frequency components.

If the result of the existing implementation does not match the intention for this function, I'd be happy to contribute a fix. And if the results do match intention and I misunderstood, then I'd be happy to contribute an explanation of how to extract the steady-state amplitude in the documentation.

**Comment by ccuetom** [comment]
Thanks for pointing this out, @dsleiter.

I think, given our intended use of this function, it makes sense to calculate the `np.fft.fft` using `forward` to make sure that the amplitude information can be interpreted directly like in your example.

Could I ask you to make this change and submit a PR with it?

**Comment by dsleiter** [comment]
Ok, great. I'll start working on the PR!
