### ISSUE TITLE
Poor inversion results when using linear transducers.

### ISSUE THREAD

**Issue by haoopan** [trustimaging/stride#65]
Dear author，
Stride is a great piece of work, and I'm following it. First, when I use the transducers with the default `elliptical` geometry, `problem.plot() ` looks like this:
![problem1](https://github.com/trustimaging/stride/assets/35628413/a378a8d9-502d-4010-8ce0-690d9d70b814)
And the corresponding inversion result is as follows:
![result1](https://github.com/trustimaging/stride/assets/35628413/28608088-a2d5-4674-9c7c-6bcda54c93e6)
It looks like the inversion result is good!
However, when I changed the transducer geometry to a **linear** arrangement, `problem.plot() ` looks like this:
![problem2](https://github.com/trustimaging/stride/assets/35628413/cc66990a-974c-447e-9d90-b1d947d6e017)
And the corresponding inversion result is as follows:
![result2](https://github.com/trustimaging/stride/assets/35628413/b4ab5e22-15b4-446e-9864-b544f5fab38b)
You can see that the result is **very poor** at this point, and it is almost impossible to get any sound velocity distribution. Do you know the reason for this result, and how to make the linear transducer also get a correct inversion result? I'm looking forward your reply!

Yours
Sincerely

**Comment by oscarbates** [comment]
Hi hoopan, we're glad you like the library and thanks for you comment.

Unfortunately, this is not a bug or issue with stride. Reflection sound speed imaging is very difficult and I recommend a literature review if you want to understand this in full
