### ISSUE TITLE
How to modify the breast2D 01_script_forward.py to support GPU?

### ISSUE THREAD

**Issue by jinshanmu** [trustimaging/stride#83]
I have successfully installed the NVIDIA HPC SDK 22.11

> nvc --version
> nvc++ --version
> nvfortran --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Wed_Sep_21_10:33:58_PDT_2022
> Cuda compilation tools, release 11.8, V11.8.89
> Build cuda_11.8.r11.8/compiler.31833905_0
> 
> nvc 22.11-0 64-bit target on x86-64 Linux -tp skylake-avx512 
> NVIDIA Compilers and Tools
> Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
> 
> nvc++ 22.11-0 64-bit target on x86-64 Linux -tp skylake-avx512 
> NVIDIA Compilers and Tools
> Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
> 
> nvfortran 22.11-0 64-bit target on x86-64 Linux -tp skylake-avx512 
> NVIDIA Compilers and Tools
> Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

and set the environmental variables, 

> export NVARCH=`uname -s`_`uname -m`
> export NVCOMPILERS=/opt/nvidia/hpc_sdk
> export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/22.11/compilers/man
> export PATH=$NVCOMPILERS/$NVARCH/22.11/compilers/bin:$PATH
> export PATH=$NVCOMPILERS/$NVARCH/22.11/comm_libs/mpi/bin:$PATH
> export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/22.11/comm_libs/mpi/man
> 
> export HPCSDK_HOME=/opt/nvidia/hpc_sdk/Linux_x86_64/22.11
> export NVHPC_CUDA_HOME=$HPCSDK_HOME/cuda
> export CUDA_ROOT=$HPCSDK_HOME/cuda/bin
> export PATH=$HPCSDK_HOME/compilers/bin/:$PATH
> export LD_LIBRARY_PATH=$HPCSDK_HOME/compilers/lib/:$LD_LIBRARY_PATH
> export LD_LIBRARY_PATH=$HPCSDK_HOME/cuda/lib/:$LD_LIBRARY_PATH
> export LD_LIBRARY_PATH=$HPCSDK_HOME/cuda/lib64/:$LD_LIBRARY_PATH
> export LD_LIBRARY_PATH=$HPCSDK_HOME/math_libs/lib64/:$LD_LIBRARY_PATH
> export LD_LIBRARY_PATH=$HPCSDK_CUPTI/lib64/:$LD_LIBRARY_PATH

with GPU well functional on PyTorch.

> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce RTX 4080        Off | 00000000:3B:00.0  On |                  N/A |
> | 38%   34C    P2              34W / 320W |   1014MiB / 16376MiB |      1%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
>                                                                                          
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |    0   N/A  N/A      3282      G   /usr/lib/xorg/Xorg                          265MiB |
> |    0   N/A  N/A      3625      G   /usr/bin/gnome-shell                         47MiB |
> |    0   N/A  N/A      4063      G   /usr/libexec/xdg-desktop-portal-gnome        63MiB |
> |    0   N/A  N/A      4979      G   /usr/bin/nautilus                           128MiB |
> |    0   N/A  N/A      5015      G   /usr/bin/gnome-text-editor                   72MiB |
> |    0   N/A  N/A    110687      G   /usr/bin/gnome-system-monitor                17MiB |
> |    0   N/A  N/A    610076      G   ...erProcess --variations-seed-version       34MiB |
> |    0   N/A  N/A    615439      G   ...onEnabled --variations-seed-version       35MiB |
> |    0   N/A  N/A   2226030      G   ...erProcess --variations-seed-version       16MiB |
> |    0   N/A  N/A   2530401      C   python                                      288MiB |
> +---------------------------------------------------------------------------------------+

I then tested the following script

```
from devito import *
import matplotlib.pyplot as plt

nx, ny = 100, 100
grid = Grid(shape=(nx, ny))

u = TimeFunction(name='u', grid=grid, space_order=2, save=200)
c = Constant(name='c')

eqn = Eq(u.dt, c * u.laplace)

step = Eq(u.forward, solve(eqn, u.forward))

xx, yy = np.meshgrid(np.linspace(0., 1., nx, dtype=np.float32),
                     np.linspace(0., 1., ny, dtype=np.float32))
r = (xx - .5) ** 2. + (yy - .5) ** 2.
u.data[0, np.logical_and(.05 <= r, r <= .1)] = 1.

op = Operator([step], platform='nvidiaX', opt=('advanced', {'gpu-fit': u}))

stats = op.apply(dt=5e-05, c=.5)

plt.rcParams['figure.figsize'] = (20, 20)
for i in range(1, 6):
    plt.subplot(1, 6, i)
    plt.imshow(u.data[(i - 1) * 40])
plt.show()
```
to make sure Devito can be working on GPU (although strangely very slow ~4s).

However, when I tried the breast2D forward example 01_script_forward.py, 
I was either still running on CPU using
`pde = IsoAcousticDevito.remote(grid=problem.grid, len=runtime.num_workers, platform='nvidia-acc')`
or getting errors using
`await forward(problem, pde(platform='nvidia-acc'), vp)`.

Any suggestions on how to resolve this issue? Thank you!

**Comment by ccuetom** [comment]
`pde = IsoAcousticDevito.remote(grid=problem.grid, len=runtime.num_workers, platform='nvidia-acc')` and `await forward(problem, pde(platform='nvidia-acc'), vp)` doesn't have any effect, you need to do `await forward(problem, pde, vp, platform='nvidia-acc')`

**Comment by jinshanmu** [comment]
> `pde = IsoAcousticDevito.remote(grid=problem.grid, len=runtime.num_workers, platform='nvidia-acc')` and `await forward(problem, pde(platform='nvidia-acc'), vp)` doesn't have any effect, you need to do `await forward(problem, pde, vp, platform='nvidia-acc')`

I changed to `await forward(problem, pde, vp, platform='nvidia-acc')` and it was indeed running on GPU! Thank you!
