### ISSUE TITLE
Errors met running breast2D 01_script_forward.py on GPU

### ISSUE THREAD

**Issue by jinshanmu** [trustimaging/stride#84]
I tried to run the breast2D forward example 01_script_forward.py on GPU and numerous errors popped up:

> 2024-07-23 00:19:10,460 - INFO       MONITOR         Listening at <CommsManager object at 140048575150864, uid=monitor, address=server-Z11PA-D8-Series, port=3002, state=connected>
> 2024-07-23 00:19:12,089 - INFO       MONITOR         Listening at <NODE:0 | WORKER:0-1>
> 2024-07-23 00:19:14,279 - INFO       HEAD            Listening at <CommsManager object at 124088198154768, uid=head, address=server-Z11PA-D8-Series, port=3016, state=connected>
> 2024-07-23 00:19:18,699 - PERF       WORKER:0:0      Default Devito configuration:
> 2024-07-23 00:19:18,699 - PERF       WORKER:0:0      	 * autotuning=['aggressive', 'runtime']
> 2024-07-23 00:19:18,699 - PERF       WORKER:0:0      	 * develop-mode=False
> 2024-07-23 00:19:18,699 - PERF       WORKER:0:0      	 * mpi=False
> 2024-07-23 00:19:18,699 - PERF       WORKER:0:0      	 * log-level=DEBUG
> 2024-07-23 00:19:18,699 - PERF       WORKER:0:0      	 * language=openmp
> 2024-07-23 00:19:20,536 - PERF       HEAD            
> 
> 2024-07-23 00:19:20,536 - PERF       HEAD            Giving shot 0 to worker:0:0 (0 out of 128)
> 2024-07-23 00:19:20,575 - PERF       WORKER:0:0      (ShotID 0) Preparing to run state for shot
> 2024-07-23 00:19:20,575 - PERF       WORKER:0:0      (ShotID 0) Selected boundary type sponge_boundary_2
> 2024-07-23 00:19:20,577 - PERF       WORKER:0:0      (ShotID 0) Estimated bandwidth for the propagated wavelet 0.255-0.735 MHz
> 2024-07-23 00:19:20,577 - WARNING    WORKER:0:0      (ShotID 0) Spatial grid spacing (0.500 mm | 3.973 PPW) is higher than dispersion limit (0.397 mm | 5.000 PPW)
> 2024-07-23 00:19:20,577 - PERF       WORKER:0:0      (ShotID 0) Time grid spacing (0.080 μs | 26%) is below OT2 limit (0.136 μs)
> 2024-07-23 00:19:20,577 - PERF       WORKER:0:0      (ShotID 0) Selected undersampling level 4
> 2024-07-23 00:19:20,577 - PERF       WORKER:0:0      (ShotID 0) Selected time stepping scheme OT2
> 2024-07-23 00:19:20,654 - PERF       WORKER:0:0      Operator `acoustic_iso_state` instance configuration:
> 2024-07-23 00:19:20,654 - PERF       WORKER:0:0      	 * name=acoustic_iso_state
> 2024-07-23 00:19:20,654 - PERF       WORKER:0:0      	 * subs={h_x: 0.0005, h_y: 0.0005, dt: 8e-08}
> 2024-07-23 00:19:20,654 - PERF       WORKER:0:0      	 * opt=advanced
> 2024-07-23 00:19:20,654 - PERF       WORKER:0:0      	 * autotuning=off
> 2024-07-23 00:19:20,654 - PERF       WORKER:0:0      	 * compiler=nvc
> 2024-07-23 00:19:20,655 - PERF       WORKER:0:0      	 * language=openacc
> 2024-07-23 00:19:20,655 - PERF       WORKER:0:0      	 * platform=nvidiaX
> 2024-07-23 00:19:20,655 - PERF       WORKER:0:0      	 * devicecreate=(p(t, x, y),)
> 2024-07-23 00:19:26,138 - PERF       WORKER:0:0      Operator `acoustic_iso_state` generated in 5.49 s
> 2024-07-23 00:19:26,138 - PERF       WORKER:0:0        * lowering.Clusters: 3.87 s (70.6 %)
> 2024-07-23 00:19:26,138 - PERF       WORKER:0:0           * specializing.Clusters: 2.41 s (44.0 %)
> 2024-07-23 00:19:26,138 - PERF       WORKER:0:0              * fuse: 1.46 s (26.7 %)
> 2024-07-23 00:19:26,138 - PERF       WORKER:0:0        * lowering.IET: 1.12 s (20.5 %)
> 2024-07-23 00:19:26,139 - PERF       WORKER:0:0      Flops reduction after symbolic optimization: [338 --> 213]
> 2024-07-23 00:19:26,474 - INFO       WORKER:0:0      recompiling for non-existent cache dir (/tmp/devito-codepy-uid1000/f6c4c18/f0fd1bba5365d854ee62bf825f480718).
> nvc++ -g -fPIC -std=c++11 -gpu=pinned -mp -acc:gpu -fast -shared /tmp/devito-jitcache-uid1000/f6c4c189b54c066515342d10171f322069fb735d.cpp -lm -o /tmp/devito-jitcache-uid1000/f6c4c189b54c066515342d10171f322069fb735d.so
> "/usr/include/stdlib.h", line 141: error: identifier "_Float32" is undefined
>   extern _Float32 strtof32 (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 147: error: identifier "_Float64" is undefined
>   extern _Float64 strtof64 (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 153: error: identifier "_Float128" is undefined
>   extern _Float128 strtof128 (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 159: error: identifier "_Float32x" is undefined
>   extern _Float32x strtof32x (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 165: error: identifier "_Float64x" is undefined
>   extern _Float64x strtof64x (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 299: error: identifier "_Float32" is undefined
>   		       _Float32 __f)
>   		       ^
> 
> "/usr/include/stdlib.h", line 305: error: identifier "_Float64" is undefined
>   		       _Float64 __f)
>   		       ^
> 
> "/usr/include/stdlib.h", line 311: error: identifier "_Float128" is undefined
>   			_Float128 __f)
>   			^
> 
> "/usr/include/stdlib.h", line 317: error: identifier "_Float32x" is undefined
>   			_Float32x __f)
>   			^
> 
> "/usr/include/stdlib.h", line 323: error: identifier "_Float64x" is undefined
>   			_Float64x __f)
>   			^
> 
> "/usr/include/stdlib.h", line 436: error: identifier "_Float32" is undefined
>   extern _Float32 strtof32_l (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 443: error: identifier "_Float64" is undefined
>   extern _Float64 strtof64_l (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 450: error: identifier "_Float128" is undefined
>   extern _Float128 strtof128_l (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 457: error: identifier "_Float32x" is undefined
>   extern _Float32x strtof32x_l (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/stdlib.h", line 464: error: identifier "_Float64x" is undefined
>   extern _Float64x strtof64x_l (const char *__restrict __nptr,
>          ^
> 
> "/usr/include/c++/13/bits/std_abs.h", line 142: error: identifier "__builtin_fabsf128" is undefined
>       return __builtin_fabsf128(__x);
>              ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 53: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (acos,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 55: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (asin,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 57: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (atan,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 59: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (atan2,, (_Mdouble_ __y, _Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 62: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (cos,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 64: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (sin,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 66: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (tan,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 71: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (cosh,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 73: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (sinh,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 75: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (tanh,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 79: error: identifier "_Float32" is undefined
>   __MATHDECL_VEC (void,sincos,,
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 85: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (acosh,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 87: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (asinh,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 89: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (atanh,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 95: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (exp,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 98: error: identifier "_Float32" is undefined
>   __MATHCALL (frexp,, (_Mdouble_ __x, int *__exponent));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 101: error: identifier "_Float32" is undefined
>   __MATHCALL (ldexp,, (_Mdouble_ __x, int __exponent));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 104: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (log,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 107: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (log10,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 110: error: identifier "_Float32" is undefined
>   __MATHCALL (modf,, (_Mdouble_ __x, _Mdouble_ *__iptr)) __nonnull ((2));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 114: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (exp10,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 119: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (expm1,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 122: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (log1p,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 125: error: identifier "_Float32" is undefined
>   __MATHCALL (logb,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 130: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (exp2,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 133: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (log2,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 140: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 143: error: identifier "_Float32" is undefined
>   __MATHCALL (sqrt,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 147: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (hypot,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 152: error: identifier "_Float32" is undefined
>   __MATHCALL_VEC (cbrt,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 159: error: identifier "_Float32" is undefined
>   __MATHCALLX (ceil,, (_Mdouble_ __x), (__const__));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 162: error: identifier "_Float32" is undefined
>   __MATHCALLX (fabs,, (_Mdouble_ __x), (__const__));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 165: error: identifier "_Float32" is undefined
>   __MATHCALLX (floor,, (_Mdouble_ __x), (__const__));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 168: error: identifier "_Float32" is undefined
>   __MATHCALL (fmod,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 198: error: identifier "_Float32" is undefined
>   __MATHCALLX (copysign,, (_Mdouble_ __x, _Mdouble_ __y), (__const__));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 203: error: identifier "_Float32" is undefined
>   __MATHCALL (nan,, (const char *__tagb));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 220: error: identifier "_Float32" is undefined
>   __MATHCALL (j0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 220: error: expected a ";"
>   __MATHCALL (j0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 220: error: "_Float32" is not a type name
>   __MATHCALL (j0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 220: error: expected a ";"
>   __MATHCALL (j0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 221: error: "_Float32" is not a type name
>   __MATHCALL (j1,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 221: error: expected a ";"
>   __MATHCALL (j1,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 221: error: expected a ";"
>   __MATHCALL (j1,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 222: error: "_Float32" is not a type name
>   __MATHCALL (jn,, (int, _Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 223: error: "_Float32" is not a type name
>   __MATHCALL (y0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 223: error: expected a ";"
>   __MATHCALL (y0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 223: error: expected a ";"
>   __MATHCALL (y0,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 224: error: "_Float32" is not a type name
>   __MATHCALL (y1,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 224: error: expected a ";"
>   __MATHCALL (y1,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 224: error: expected a ";"
>   __MATHCALL (y1,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 225: error: "_Float32" is not a type name
>   __MATHCALL (yn,, (int, _Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 231: error: "_Float32" is not a type name
>   __MATHCALL_VEC (erf,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 231: error: expected a ";"
>   __MATHCALL_VEC (erf,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 231: error: expected a ";"
>   __MATHCALL_VEC (erf,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 232: error: "_Float32" is not a type name
>   __MATHCALL_VEC (erfc,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 232: error: expected a ";"
>   __MATHCALL_VEC (erfc,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 232: error: expected a ";"
>   __MATHCALL_VEC (erfc,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 233: error: "_Float32" is not a type name
>   __MATHCALL (lgamma,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 233: error: expected a ";"
>   __MATHCALL (lgamma,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 233: error: expected a ";"
>   __MATHCALL (lgamma,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 238: error: "_Float32" is not a type name
>   __MATHCALL (tgamma,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 238: error: expected a ";"
>   __MATHCALL (tgamma,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 238: error: expected a ";"
>   __MATHCALL (tgamma,, (_Mdouble_));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 252: error: "_Float32" is not a type name
>   __MATHCALL (lgamma,_r, (_Mdouble_, int *__signgamp));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 252: error: type name is not allowed
>   __MATHCALL (lgamma,_r, (_Mdouble_, int *__signgamp));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 252: error: identifier "__signgamp" is undefined
>   __MATHCALL (lgamma,_r, (_Mdouble_, int *__signgamp));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 252: error: expected a ";"
>   __MATHCALL (lgamma,_r, (_Mdouble_, int *__signgamp));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 252: error: type name is not allowed
>   __MATHCALL (lgamma,_r, (_Mdouble_, int *__signgamp));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 252: error: expected a ";"
>   __MATHCALL (lgamma,_r, (_Mdouble_, int *__signgamp));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 259: error: "_Float32" is not a type name
>   __MATHCALL (rint,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 259: error: expected a ")"
>   __MATHCALL (rint,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 259: error: expected a ";"
>   __MATHCALL (rint,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 259: error: expected a ")"
>   __MATHCALL (rint,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 259: error: expected a ";"
>   __MATHCALL (rint,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 262: error: "_Float32" is not a type name
>   __MATHCALL (nextafter,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 262: error: expected a ")"
>   __MATHCALL (nextafter,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 262: error: expected a ";"
>   __MATHCALL (nextafter,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 262: error: expected a ")"
>   __MATHCALL (nextafter,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 262: error: expected a ";"
>   __MATHCALL (nextafter,, (_Mdouble_ __x, _Mdouble_ __y));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 269: error: "_Float32" is not a type name
>   __MATHCALL (nextdown,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 269: error: expected a ")"
>   __MATHCALL (nextdown,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 269: error: expected a ";"
>   __MATHCALL (nextdown,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 269: error: expected a ")"
>   __MATHCALL (nextdown,, (_Mdouble_ __x));
>   ^
> 
> "/usr/include/x86_64-linux-gnu/bits/mathcalls.h", line 269: error: expected a ";"
>   __MATHCALL (nextdown,, (_Mdouble_ __x));
>   ^
> 
> Error limit reached.
> 100 errors detected in the compilation of "/tmp/devito-jitcache-uid1000/f6c4c189b54c066515342d10171f322069fb735d.cpp".
> Compilation terminated.
> FAILED compiler invocation: nvc++ -g -fPIC -std=c++11 -gpu=pinned -mp -acc:gpu -fast -shared /tmp/devito-jitcache-uid1000/f6c4c189b54c066515342d10171f322069fb735d.cpp -lm -o /tmp/devito-jitcache-uid1000/f6c4c189b54c066515342d10171f322069fb735d.so
> Traceback (most recent call last):
>   File "/home/server/stride/stride_examples/examples/breast2D/01_script_forward.py", line 68, in <module>
>     mosaic.run(main)
>   File "/home/server/stride/mosaic/__init__.py", line 283, in run
>     loop.run(_main)
>   File "/home/server/stride/mosaic/utils/event_loop.py", line 291, in run
>     return self._loop.run_until_complete(coro(*args, **kwargs))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
>   File "/home/server/stride/mosaic/__init__.py", line 280, in _main
>     await main(_runtime)
>   File "/home/server/stride/stride_examples/examples/breast2D/01_script_forward.py", line 64, in main
>     await forward(problem, pde, vp, platform='nvidia-acc')
>   File "/home/server/stride/stride/__init__.py", line 165, in forward
>     await loop
>   File "/home/server/stride/mosaic/runtime/runtime.py", line 378, in _async_for
>     res = await task
>           ^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
>     return f.result()  # May raise f.exception().
>            ^^^^^^^^^^
>   File "/home/server/stride/mosaic/runtime/runtime.py", line 369, in call
>     res = await func(_worker, *iters)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/stride/stride/__init__.py", line 144, in loop
>     traces = await pde(wavelets, *published_args,
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/stride/mosaic/core/task.py", line 802, in result
>     await self
>   File "/home/server/stride/mosaic/core/task.py", line 872, in __await__
>     yield from self._done_future.__await__()
>   File "/home/server/stride/mosaic/utils/event_loop.py", line 83, in __await__
>     return (yield from self._future.__await__())
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/stride/mosaic/core/tessera.py", line 385, in send_exception
>     yield
> ^^^^^^^^^^
>   File "/home/server/stride/mosaic/core/tessera.py", line 361, in call_safe
>     result = await future
> ^^^^^^^^^^^
>   File "/home/server/stride/stride/core.py", line 669, in __call__
>     outputs = self.forward(*args, **kwargs)
> ^^^^^^^^^^^^^^^
>   File "/home/server/stride/stride/physics/problem_type.py", line 74, in forward
>     self.before_forward(*args, **kwargs)
>   ^^^^^^^^^^^^^^^^^
>   File "/home/server/stride/stride/physics/iso_acoustic/devito.py", line 419, in before_forward
>     self.state_operator.compile()
> ^^^^^^^^^^^^^^^
>   File "/home/server/stride/stride/physics/common/devito.py", line 991, in compile
>     self.devito_operator.cfunction
>   ^^^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/devito/operator/operator.py", line 750, in cfunction
>     self._jit_compile()
> ^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/devito/operator/operator.py", line 736, in _jit_compile
>     recompiled, src_file = self._compiler.jit_compile(self._soname, str(self))
> ^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/devito/arch/compiler.py", line 376, in jit_compile
>     _, _, _, recompiled = compile_from_string(self, target, code, src_file,
> ^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/codepy/jit.py", line 439, in compile_from_string
>     toolchain.build_extension(ext_file, source_paths, debug=debug)
> ^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/codepy/toolchain.py", line 211, in build_extension
>     raise CompileError("module compilation failed")
> ^^^^^^^^^^^^^^^
> codepy.CompileError: module compilation failed
> Traceback (most recent call last):
>   File "/home/server/anaconda3/envs/stride/bin/mrun_", line 33, in <module>
>     sys.exit(load_entry_point('stride', 'console_scripts', 'mrun_')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/stride/mosaic/cli/mrun.py", line 163, in go
>     loop.run(main)
>   File "/home/server/stride/mosaic/utils/event_loop.py", line 291, in run
>     return self._loop.run_until_complete(coro(*args, **kwargs))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
>   File "/home/server/stride/mosaic/cli/mrun.py", line 160, in main
>     await loop.run_in_executor(run_head)
>   File "/home/server/anaconda3/envs/stride/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/server/stride/mosaic/cli/mrun.py", line 157, in run_head
>     raise RuntimeError('Process ended with code: %d' % process.returncode)
> RuntimeError: Process ended with code: 1

The CPU implementation is good. My GPU is NVIDIA GeForce RTX 4080, with cuda 11.8 and NVIDIA HPC SDK 22.11 successfully installed. 

Any suggestions on solving this issue will be helpful. Thank you!

**Comment by ccuetom** [comment]
This looks like your path is not correctly set up. You may have conflicting compilers and libraries in your path, so I would carefully check this.

**Comment by jinshanmu** [comment]
> This looks like your path is not correctly set up. You may have conflicting compilers and libraries in your path, so I would carefully check this.

I just found I'm using Ubuntu 24.04 and I will try to downgrade to 22.04 and see.

**Comment by jinshanmu** [comment]
> > This looks like your path is not correctly set up. You may have conflicting compilers and libraries in your path, so I would carefully check this.
> 
> I just found I'm using Ubuntu 24.04 and I will try to downgrade to 22.04 and see.

The compilation errors resolved after I downgraded to Ubuntu 22.04 from 24.04. The highest Ubuntu version that NVIDIA HPC SDK 22.11 supports is 22.04.
