### ISSUE TITLE
How much memory does the breast3D example need?

### ISSUE THREAD

**Issue by jinshanmu** [trustimaging/stride#85]
I tried to run the breast3D example 02_script_inverse.py on Intel® Xeon(R) Gold 6133 CPU @ 2.50GHz × 80 with 256 GB memory using openmp+gcc but it still returned MemoryOverflowError. How much memory do I need in total to run this script? Or does this involves the configuration of the number of workers and threads? I tried to use multiple workers.

**Comment by ccuetom** [comment]
How many workers did you try to use?

**Comment by jinshanmu** [comment]
> How many workers did you try to use?

I tried multiple values, the number of workers can only be 1 which takes up ~130GB, once over the memory will overflow.

**Comment by ccuetom** [comment]
That makes sense, FWI is a very memory-hungry algorithm, especially in 3D. You can tune the memory consumption by using `save_undersampling` and by tweaking the number of timesteps, timestep size, and grid spacing.
